#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/dell/source/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/dell/source/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/dell/workspace/locmea/data/L5bPCmodelsEH/mod/x86_64/.libs/libnrnmech.so" "$@"
